# Generated by Django 5.0.6 on 2024-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
                ('generic_name', models.CharField(max_length=100)),
                ('manufacture', models.CharField(max_length=66)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batch_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
